import "./globals.css";
import Nav from "./Nav";
import Fav from "./footer"
export const metadata = {
  title: "Installa",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-black">
        {/* Common Navigation Bar */}
        <Nav />
        {/* Page Content */}
        <main >{children}</main>
        <Fav />
      </body>
    </html>
  );
}
